### ISSUE TITLE
Change DOM object creation

### ISSUE THREAD

**Issue by otacke** [ymdahi/h5p-cardblock#4]
Here you're implicitly creating a DOM object and then creating a variable holding it by searching for that very object. You could simply create that DOM object first and attach it to the container in one go. More efficient and you won't have to use the indexed card CSS class.

https://github.com/ymdahi/h5p-cardblock/blob/23c666e075b6c478172ef8ce6a532d8ce9ee379e/scripts/cardblock.js#L27-L28

**Comment by ymdahi** [comment]
Good point. I've adopted your recommendation here:

https://github.com/ymdahi/h5p-cardblock/blob/a9209b61c0ccd86793d30e7d87643f2729580e28/scripts/cardblock.js#L29-L30

Also was able to get rid of the indexed css class.

Open to other suggestions.

**Comment by otacke** [comment]
More suggestions depend on your taste, I guess :-)

I also started using jQuery within H5P, but switched to vanilla JavaScript when I found https://h5ptechnology.atlassian.net/browse/HFP-874 It's an old issue and may never be put into practice, but it makes a valid point: jQuery being obsolete, kind of. I wouldn't want to change all my code in the future :-)

**Comment by ymdahi** [comment]
I did consider writing in vanilla js. for now, as this is my first attempt to create a (very simple) library, I wanted to get a better sense of the h5p api (and all of the documentation and examples use jquery).

Next library might have a more modern toolchain

**Comment by otacke** [comment]
No pressure :-)
