### ISSUE TITLE
Searching for DOM objects

### ISSUE THREAD

**Issue by otacke** [ymdahi/h5p-cardblock#5]
You could get rid of the query selection here and in line 48 by simply creating a variable holding the card-body element above. If you're creating dom objects yourself, it's rarely necessary to rely on them being in the DOM, and then there's not really a need to search for them in the DOM.

https://github.com/ymdahi/h5p-cardblock/blob/23c666e075b6c478172ef8ce6a532d8ce9ee379e/scripts/cardblock.js#L42

**Comment by ymdahi** [comment]
Another good point, I've adopted this as well:

https://github.com/ymdahi/h5p-cardblock/blob/a9209b61c0ccd86793d30e7d87643f2729580e28/scripts/cardblock.js#L41-L51

Definitely makes reading the code easier.
