### ISSUE TITLE
Using a reference variable 

### ISSUE THREAD

**Issue by otacke** [ymdahi/h5p-cardblock#6]
You are using this.options.cards[i].params a lot, so it might make sense to create a reference variable such as params and use this one instead. Would make the code more readable.

https://github.com/ymdahi/h5p-cardblock/blob/23c666e075b6c478172ef8ce6a532d8ce9ee379e/scripts/cardblock.js#L31

**Comment by ymdahi** [comment]
Like this?

https://github.com/ymdahi/h5p-cardblock/blob/a9209b61c0ccd86793d30e7d87643f2729580e28/scripts/cardblock.js#L28

...

https://github.com/ymdahi/h5p-cardblock/blob/a9209b61c0ccd86793d30e7d87643f2729580e28/scripts/cardblock.js#L33

**Comment by otacke** [comment]
@ymdahi Yup!
I think you also go for something like
` var currentParams = this.options.cards[i].params || {};`
instead, because you don't use the reference to the current card element. But maybe you plan to in the future ...

**Comment by ymdahi** [comment]
Yes, I might want to add things like background color, button color, styles, etc., We'll see...
