### ISSUE TITLE
Use of CC BY-SA

### ISSUE THREAD

**Issue by otacke** [ymdahi/h5p-cardblock#7]
I know that some example code on the specs page shows "Creative Commons BY-SA" license, but it's rather an odd license for source code. Are you using it intentionally?

https://github.com/ymdahi/h5p-cardblock/blob/23c666e075b6c478172ef8ce6a532d8ce9ee379e/library.json#L10

**Comment by ymdahi** [comment]
Thanks for the feedback! I'm fairly new to h5p dev so your feedback is appreciated. I'll go through these fixes this week.

The license is not intentional - I see that you guys use the MIT license, so I'll adopt that as well.

**Comment by otacke** [comment]
@ymdahi You're welcome! Just to clarify: I'm not a member of the H5P core team, but a "prolific contributor" as I was called lately :-D Feel free to reach out if you need support.

**Comment by ymdahi** [comment]
Switched to MIT license 👍
