### ISSUE TITLE
IE11 doesn't support object-fit

### ISSUE THREAD

**Issue by otacke** [ymdahi/h5p-cardblock#8]
IE11 doesn't support the object-fit CSS property, cmp. https://caniuse.com/#feat=object-fit Since H5P still supports that old browser, you may want to achieve the effect differently.

https://github.com/ymdahi/h5p-cardblock/blob/23c666e075b6c478172ef8ce6a532d8ce9ee379e/styles/cardblock.css#L33

**Comment by ymdahi** [comment]
Unfortunately, couldn't find an alternative to object-fit (or a proper shim). So for now, we'll just have to leave that cool feature out:

https://github.com/ymdahi/h5p-cardblock/blob/e99428ad196647642d6a444d649146bce4707b39/styles/cardblock.css#L30-L35

**Comment by otacke** [comment]
@ymdahi I've never used the _object-fit_ property, but I assume you could use the _background_ property of an element to set the image. There's a sub(property) _background-size_ that accepts the value cover.

**Comment by otacke** [comment]
Just leaving as a note, might be related: Images get stretched or squeezed if they don't have the proper aspect ratio.

**Comment by ymdahi** [comment]
As suggested, using the image as a background-image and using `backgorund-size: cover` to mitigate image stretching/squeezing when it doesn't fit the aspect ratio.
